name: Continuous Integration Checks

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --extend-ignore=E402
          python3 -m flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --extend-ignore=E402
      - name: Test with pytest 
        run: |
          python3 -m pytest tests --cov --cov-report=xml:cov.xml --cov-report=html:cov_html
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            ./cov.xml
            ./cov_html