name: "test ZULU CI"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r 'sierra_tests/requirements.txt'
        pip3 install rst2pdf
    - name: Run Python script and save output to file
      run: |
        python3 sierra_tests/sierra_script.py > output.txt
    - name: Convert TXT to PDF
      run: |
        rst2pdf output.txt -o output.pdf
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output.pdf